# Generated by Django 4.2.5 on 2025-07-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=323497755341342665048515816667348579315, unique=True),
        ),
    ]
