# Generated by Django 4.2.5 on 2025-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=141250530821834395578441759769475784790, unique=True),
        ),
    ]
