# Generated by Django 4.2.5 on 2025-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=231284818795071528828090726774049219444, unique=True),
        ),
    ]
