# Generated by Django 4.2.5 on 2025-07-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=29174956056350020489875576746165593148, unique=True),
        ),
    ]
