# Generated by Django 4.2.5 on 2025-07-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0038_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=160821581955039190025908427540232818926, unique=True),
        ),
    ]
