# Generated by Django 4.2.5 on 2025-07-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0039_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=206302838321911869254544295878387471976, unique=True),
        ),
    ]
