# Generated by Django 4.2.5 on 2025-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=243215639397201341620008804073511801158, unique=True),
        ),
    ]
