# Generated by Django 4.2.5 on 2025-07-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0043_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=86072652843017439197838301088087117448, unique=True),
        ),
    ]
