# Generated by Django 4.2.5 on 2025-07-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0044_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=109162798471570325802801109997772587779, unique=True),
        ),
    ]
