# Generated by Django 4.2.5 on 2025-07-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0045_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=201210034743625668347145154536438887228, unique=True),
        ),
    ]
