# Generated by Django 4.2.5 on 2025-07-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0046_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=78089810356304001881794222569683324378, unique=True),
        ),
    ]
