# Generated by Django 4.2.5 on 2025-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0048_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=44355457219679697101903515864634675497, unique=True),
        ),
    ]
