# Generated by Django 4.2.5 on 2025-09-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0049_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=180710364179921638001518711589971151328, unique=True),
        ),
    ]
