# Generated by Django 4.2.5 on 2025-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0051_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=171458099220652675629219924878756147267, unique=True),
        ),
    ]
