# Generated by Django 4.2.5 on 2025-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0052_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=138180228464342675420356506335095391267, unique=True),
        ),
    ]
