# Generated by Django 4.2.5 on 2025-09-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0053_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=211181323806502777718800584317505650248, unique=True),
        ),
    ]
