# Generated by Django 4.2.5 on 2025-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0054_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=307924774907788080886985858009632760066, unique=True),
        ),
    ]
