# Generated by Django 4.2.5 on 2025-09-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0055_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=89622190940283702664257182543471411810, unique=True),
        ),
    ]
