# Generated by Django 4.2.5 on 2025-09-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0057_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=279733838800423559909386675925131454487, unique=True),
        ),
    ]
