# Generated by Django 4.2.5 on 2025-09-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0059_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=217028997198772912461429935882916430117, unique=True),
        ),
    ]
