# Generated by Django 4.2.5 on 2025-09-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0060_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=152409864606394365036160790317868243370, unique=True),
        ),
    ]
