# Generated by Django 4.2.5 on 2025-09-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0061_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=242866048677126912091535779583234131450, unique=True),
        ),
    ]
