# Generated by Django 4.2.5 on 2025-09-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0062_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=203109692728754388033668696017282551158, unique=True),
        ),
    ]
