# Generated by Django 4.2.5 on 2025-09-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0063_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=116655601674577792403304982795833325115, unique=True),
        ),
    ]
