# Generated by Django 4.2.5 on 2025-09-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0064_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=243721747191351481342114722335530817175, unique=True),
        ),
    ]
